# https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
---
- name: install dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: repo key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: repo
  become: true
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes

- name: install docker
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: adding existing user '{{ _user }}' to group docker
  become: true
  user:
    name: "{{ _user }}"
    groups: docker
    append: yes
