---
- name: Install requirements
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: Add Docker Repo key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Get DEB architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: deb_architecture.rc != 0

- name: Add Docker Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true

- name: Install docker
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Adding existing user '{{ _user }}' to group docker
  become: true
  ansible.builtin.user:
    name: "{{ _user }}"
    groups: docker
    append: true

- name: Create a symbolic to docker-compose
  become: true
  when: docker_compose_compatibility == 'true'
  ansible.builtin.copy:
    src: docker-compose
    dest: /usr/bin/docker-compose
    mode: '755'
    owner: root
    group: root
