---
- name: install dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - lsb-release

- name: repo key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    update_cache: yes

- name: install package
  become: true
  apt:
    pkg:
      - azure-cli
