---
- name: add repo key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/chrome.gpg

- name: add repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

- name: install
  become: true
  apt:
    pkg:
      - google-chrome-stable
