---
- name: repo key
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg

- name: add repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    update_cache: yes

- name: install
  become: true
  apt:
    pkg:
    - terraform
