---
- name: Add repo key
  become: true
  ansible.builtin.apt_key:
    keyring: /etc/apt/keyrings/1password-archive-keyring.gpg
    keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

- name: Add repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
    filename: 1password

- name: Install
  become: true
  ansible.builtin.apt:
    pkg:
      - 1password
