---
- name: repo key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: repo
  become: true
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    update_cache: yes

- name: install yarn
  become: true
  apt:
    install_recommends: no
    pkg:
      - yarn
