---
- name: repo key
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/keyrings/hashicorp.gpg

- name: add repo
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp

- name: install
  become: true
  apt:
    pkg:
      - terraform
