---
- name: Remove previous version
  ansible.builtin.file:
    state: absent
    path: "{{ _install_dir }}/acorn"
    force: true

- name: Download and Install
  ansible.builtin.unarchive:
    src: "https://github.com/ainrif/acorn/releases/latest/download/acorn.zip"
    dest: "{{ _install_dir }}"
    remote_src: true

- name: Create go symlink
  ansible.builtin.file:
    src: "{{ _install_dir }}/acorn/bin/acorn"
    dest: "{{ _local_bin }}/acorn"
    state: link
